# Generated by Django 2.2 on 2019-06-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Username', models.CharField(default=None, max_length=50)),
                ('Password', models.CharField(max_length=40)),
                ('Profile', models.ImageField(upload_to='')),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
