# Generated by Django 2.2 on 2019-06-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='Profile',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
