# Generated by Django 2.2 on 2019-07-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddUser',
        ),
    ]
